[package]
name = "eccodes-sys"
version = "2.10.0"
authors = ["Ryan <rnleach@users.noreply.github.com>"]
edition = "2018"
build = "build.rs"
publish = false

[dependencies]
libc = "0.2"

[build-dependencies]
bindgen = "0.47.1"
pkg-config = "0.3.14"
